on:
  workflow_dispatch: {}
  push:
    paths:
      - 'dst/**.html'
    branches:
      - release

name: Deploy Site Changes to AWS S3

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

env:
  DEPLOY_REGION: us-east-2

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v2
      # takes 180 seconds to timeout if role doesn't exist... no need to wait that long
      timeout-minutes: 1
      with:
        aws-region: ${{ env.DEPLOY_REGION }}
        role-to-assume: arn:aws:iam::812212307632:role/github-actions/${{ github.repository }}

    - name: sync html files to s3
      id: sync-html-files
      run: |
        aws s3 sync ./dst s3://funderburgfinishes-bucket --delete --content-type text/html --exclude "*resources/*"
